#ifndef FSCONFIG_H
#define FSCONFIG_H

//#define FS_TESTING

#define NUM_OF_SENSORS          5

#define KILOBYTES               1024

#define MAX_VPAGES              500  /* Maximum Number of Virtual Pages */

#define FLASH_BLOCKS_PER_SENSOR 32  /* Number of Flash block for each sensor */

#define RAM_BLOCKS_PER_SENSOR   160 /* Number of RAM blocks each sensor is allowed to have */

/* Sensor Desc Block Configuration (FRAM) */
#define SENSORS_FRAM_START      20*KILOBYTES
#define SENSOR_0_FRAM_INDEX     SENSORS_FRAM_START
#define SENSOR_1_FRAM_INDEX     SENSOR_0_FRAM_INDEX + 4*KILOBYTES
#define SENSOR_2_FRAM_INDEX     SENSOR_1_FRAM_INDEX + 4*KILOBYTES
#define SENSOR_3_FRAM_INDEX     SENSOR_2_FRAM_INDEX + 4*KILOBYTES
#define SENSOR_4_FRAM_INDEX     SENSOR_3_FRAM_INDEX + 4*KILOBYTES


/* Sensor Data Block Configuration (Flash) */
#define SENSOR_FLASH_START     2
#define SENSOR_0_START_BLOCK   SENSOR_FLASH_START
#define SENSOR_0_END_BLOCK     SENSOR_0_START_BLOCK + FLASH_BLOCKS_PER_SENSOR
#define SENSOR_1_START_BLOCK   SENSOR_0_END_BLOCK
#define SENSOR_1_END_BLOCK     SENSOR_1_START_BLOCK + FLASH_BLOCKS_PER_SENSOR
#define SENSOR_2_START_BLOCK   SENSOR_1_END_BLOCK
#define SENSOR_2_END_BLOCK     SENSOR_2_START_BLOCK + FLASH_BLOCKS_PER_SENSOR
#define SENSOR_3_START_BLOCK   SENSOR_2_END_BLOCK
#define SENSOR_3_END_BLOCK     SENSOR_3_START_BLOCK + FLASH_BLOCKS_PER_SENSOR
#define SENSOR_4_START_BLOCK   SENSOR_3_END_BLOCK
#define SENSOR_4_END_BLOCK     SENSOR_4_START_BLOCK + FLASH_BLOCKS_PER_SENSOR


typedef enum{
  FS_SUCCESS=0,
  FS_FAILED,
  FS_NO_RAM_BLOCKS,
  FS_NO_FLASH_BLOCKS,
  FS_UNKNOWN_ERROR,
  FS_INCORRECT_INDEX
}FS_RETURN_T;


#endif